site_name: cITMre package
site_url: https://SergioFinances.github.io/citmre_development_python/
nav:
  - Home: index.md
  - Get started: Get_Started.md
  - Reference: references.md

theme:
  name: material
  logo: https://i.ibb.co/s6db4M4/logo.png

extra:
  license: C:\Users\sergiosierra\OneDrive - itm.edu.co\Con Sergio Sierra\citmre\citmre_development_python\LICENCE.txt


